// File khusus untuk menyimpan Bank Soal BO2
const questionBank = {
    prakerja: [
        { q: "Pada tahun berapakah Program Kartu Prakerja pertama kali diluncurkan secara resmi oleh pemerintah?", o: ["2018", "2019", "2020", "2021"], a: 2 },
        { q: "Siapakah nama Direktur Eksekutif Manajemen Pelaksana Program Kartu Prakerja (PMO) saat ini?", o: ["Airlangga Hartarto", "Sri Mulyani", "Denni Puspa Purbasari", "Nadiem Makarim"], a: 2 },
        { q: "Berapakah batas usia minimal untuk bisa mendaftar Program Kartu Prakerja?", o: ["17 Tahun", "18 Tahun", "20 Tahun", "21 Tahun"], a: 1 },
        { q: "Berapakah batas usia maksimal bagi pendaftar Program Kartu Prakerja berdasarkan aturan terbaru?", o: ["55 Tahun", "60 Tahun", "64 Tahun", "Tidak Terbatas"], a: 2 },
        { q: "Mulai tahun 2023, Kartu Prakerja beralih dari skema bantuan sosial (semi bansos) menjadi skema...", o: ["Skema Pendidikan", "Skema Normal", "Skema Bantuan Langsung", "Skema Mahasiswa"], a: 1 },
        { q: "Pada Skema Normal, berapakah total nilai besaran beasiswa (saldo) yang diberikan KHUSUS untuk membeli pelatihan?", o: ["Rp 1.000.000", "Rp 2.400.000", "Rp 3.500.000", "Rp 4.200.000"], a: 2 },
        { q: "Berapakah insentif pasca pelatihan (uang tunai) yang didapat peserta jika menyelesaikan pelatihan pada Skema Normal?", o: ["Rp 600.000", "Rp 1.000.000", "Rp 2.400.000", "Rp 3.500.000"], a: 0 },
        { q: "Peserta Prakerja akan mendapatkan insentif tambahan jika mengisi Survei Evaluasi. Berapa nilai insentif per surveinya?", o: ["Rp 25.000", "Rp 50.000", "Rp 100.000", "Rp 150.000"], a: 1 },
        { q: "Berapa lama batas waktu yang diberikan kepada peserta untuk membeli pelatihan pertama sejak dinyatakan lolos gelombang?", o: ["7 Hari", "15 Hari", "30 Hari", "60 Hari"], a: 1 },
        { q: "Kementerian apakah yang menjadi 'induk' atau koordinator utama dari Program Kartu Prakerja?", o: ["Kemenaker", "Kemenkeu", "Kemenko Perekonomian", "Kemendikbud"], a: 2 },
        { q: "Manakah dari golongan berikut yang TIDAK BOLEH mendaftar Kartu Prakerja?", o: ["Korban PHK", "Pencari Kerja Baru", "PNS / TNI / Polri", "Pelaku UMKM"], a: 2 },
        { q: "Apa tujuan utama dari Program Kartu Prakerja pada Skema Normal saat ini?", o: ["Bantuan sembako", "Meningkatkan kompetensi kerja & kewirausahaan", "Memberi modal usaha langsung", "Membayar cicilan masyarakat"], a: 1 },
        { q: "Dalam pelaksanaannya, terdapat fitur rekomendasi lowongan kerja di dashboard Prakerja. Fitur ini disebut...", o: ["Job Recommendation", "Prakerja Karir", "Bursa Kerja Nasional", "SIPP"], a: 0 },
        { q: "Selain pelatihan Webinar/Online, Skema Normal Prakerja juga memberlakukan metode pelatihan...", o: ["Tatap Muka (Offline)", "Magang Luar Negeri", "Kuliah Jarak Jauh", "Sekolah Kedinasan"], a: 0 },
        { q: "Dalam menjaga akuntabilitas, Program Kartu Prakerja selalu diawasi secara ketat oleh lembaga negara, salah satunya adalah...", o: ["Komnas HAM", "BPK dan KPK", "Mahkamah Konstitusi", "KPU"], a: 1 }
    ],
    sejarah: [
        { q: "Naskah asli Proklamasi yang sempat dibuang ke tempat sampah diselamatkan oleh...", o: ["Sayuti Melik", "B.M. Diah", "Sukarni", "Latief H."], a: 1 },
        { q: "Kerajaan Islam pertama di Nusantara di pesisir utara Sumatera adalah...", o: ["Demak", "Mataram", "Samudera Pasai", "Banten"], a: 2 },
        { q: "Konferensi Asia Afrika (KAA) tahun 1955 diselenggarakan di kota...", o: ["Jakarta", "Surabaya", "Bandung", "Yogyakarta"], a: 2 },
        { q: "Perjanjian pengakuan kedaulatan Indonesia tahun 1949 adalah...", o: ["Linggarjati", "Renville", "Roem-Royen", "Konferensi Meja Bundar"], a: 3 },
        { q: "Pahlawan Bandung Lautan Api dengan taktik peledakan gudang amunisi adalah...", o: ["Pangeran Diponegoro", "Mohammad Toha", "Kapitan Pattimura", "Teuku Umar"], a: 1 },
        { q: "Presiden RI yang mendapat julukan 'Bapak Pembangunan' adalah...", o: ["Soekarno", "Soeharto", "B.J. Habibie", "Abdurrahman Wahid"], a: 1 },
        { q: "Raja terbesar dari Kerajaan Majapahit yang didampingi Patih Gajah Mada adalah...", o: ["Raden Wijaya", "Hayam Wuruk", "Ken Arok", "Jayanegara"], a: 1 },
        { q: "Sumpah Pemuda diikrarkan pada tanggal...", o: ["17 Agustus 1945", "1 Juni 1945", "28 Oktober 1928", "20 Mei 1908"], a: 2 },
        { q: "Organisasi pergerakan nasional pertama di Indonesia yang berdiri tahun 1908 adalah...", o: ["Sarekat Islam", "Indische Partij", "Budi Utomo", "Muhammadiyah"], a: 2 },
        { q: "Pahlawan wanita dari Aceh yang terus berjuang meski suaminya wafat adalah...", o: ["R.A. Kartini", "Cut Nyak Dien", "Martha Christina", "Dewi Sartika"], a: 1 },
        { q: "Tokoh yang mengetik teks Proklamasi kemerdekaan adalah...", o: ["Sayuti Melik", "Sukarni", "Ahmad Soebardjo", "Fatmawati"], a: 0 },
        { q: "Sistem tanam paksa (Cultuurstelsel) di Indonesia dicetuskan oleh Gubernur Jenderal...", o: ["Daendels", "Raffles", "Van den Bosch", "J.P. Coen"], a: 2 },
        { q: "Prasasti Yupa peninggalan kerajaan Hindu tertua ditemukan di...", o: ["Kutai", "Tarumanegara", "Kediri", "Singasari"], a: 0 },
        { q: "Peristiwa Rengasdengklok bertujuan untuk...", o: ["Menculik Belanda", "Mendesak Soekarno-Hatta segera proklamasi", "Membentuk tentara PETA", "Menyusun teks proklamasi"], a: 1 },
        { q: "Surat Perintah Sebelas Maret (Supersemar) dikeluarkan pada tahun...", o: ["1945", "1965", "1966", "1998"], a: 2 }
    ],
    islam: [
        { q: "Dalam Shalat Idul Fitri, jumlah takbir tambahan pada rakaat pertama dan kedua adalah...", o: ["7 dan 5", "5 dan 7", "7 dan 7", "3 dan 3"], a: 0 },
        { q: "Zakat yang wajib dikeluarkan sebelum Shalat Idul Fitri disebut...", o: ["Zakat Mal", "Zakat Profesi", "Zakat Fitrah", "Sedekah"], a: 2 },
        { q: "Puasa sunnah 6 hari yang dianjurkan setelah perayaan Idul Fitri dilakukan di bulan...", o: ["Ramadhan", "Syawal", "Dzulhijjah", "Muharram"], a: 1 },
        { q: "Tradisi saling memaafkan setelah Lebaran khas Indonesia disebut...", o: ["Tarawih", "Halal Bihalal", "Tadarus", "Nyadran"], a: 1 },
        { q: "Malaikat yang bertugas membagikan rezeki dari Allah SWT adalah...", o: ["Jibril", "Mikail", "Israfil", "Izrail"], a: 1 },
        { q: "Peristiwa turunnya Al-Quran pertama kali diperingati sebagai...", o: ["Isra Mi'raj", "Nuzulul Quran", "Maulid Nabi", "Tahun Baru Hijriyah"], a: 1 },
        { q: "Malam seribu bulan yang penuh kemuliaan di bulan Ramadhan disebut...", o: ["Lailatul Qadar", "Malam Nisfu Sya'ban", "Malam Asyura", "Malam Takbiran"], a: 0 },
        { q: "Shalat sunnah yang mengiringi shalat fardhu (sebelum/sesudah) disebut shalat...", o: ["Tahajud", "Dhuha", "Rawatib", "Hajat"], a: 2 },
        { q: "Nabi yang mendapat julukan 'Khatamul Anbiya' (Penutup Para Nabi) adalah...", o: ["Nabi Ibrahim", "Nabi Musa", "Nabi Isa", "Nabi Muhammad SAW"], a: 3 },
        { q: "Bulan kesembilan dalam kalender Hijriyah adalah...", o: ["Rajab", "Sya'ban", "Ramadhan", "Syawal"], a: 2 },
        { q: "Surah pembuka dalam Al-Quran yang wajib dibaca saat shalat adalah...", o: ["Al-Baqarah", "Yasin", "Al-Fatihah", "Al-Ikhlas"], a: 2 },
        { q: "Istri Nabi Muhammad SAW yang pertama adalah...", o: ["Aisyah", "Khadijah", "Fatimah", "Zainab"], a: 1 },
        { q: "Rukun Islam yang ketiga adalah...", o: ["Syahadat", "Shalat", "Zakat", "Puasa"], a: 2 },
        { q: "Pintu surga yang dikhususkan bagi orang-orang yang berpuasa bernama...", o: ["Ar-Raiyan", "Firdaus", "Adn", "Ma'wa"], a: 0 },
        { q: "Hukum mengeluarkan Zakat Fitrah bagi muslim yang mampu adalah...", o: ["Sunnah Muakkad", "Fardhu Kifayah", "Fardhu Ain (Wajib)", "Mubah"], a: 2 }
    ],
    agama: [
        { q: "Tokoh besar yang diakui sebagai 'Bapak Para Nabi' dalam Islam dan Kristen adalah...", o: ["Nabi Musa", "Nabi Ibrahim", "Nabi Daud", "Nabi Nuh"], a: 1 },
        { q: "Tempat ibadah suci bersejarah yang dihormati oleh Islam dan Kristen terletak di kota...", o: ["Mekkah", "Vatikan", "Yerusalem", "Madinah"], a: 2 },
        { q: "Malaikat penyampai kabar gembira (wahyu) kepada Maryam/Maria adalah...", o: ["Jibril/Gabriel", "Mikail/Michael", "Israfil", "Izrail"], a: 0 },
        { q: "Nabi bermukjizat membelah laut untuk menyelamatkan umatnya adalah...", o: ["Ibrahim", "Musa", "Isa", "Yunus"], a: 1 },
        { q: "Tokoh yang dikisahkan ditelan ikan paus raksasa adalah...", o: ["Nabi Ayub", "Nabi Daud", "Nabi Sulaiman", "Nabi Yunus/Jonah"], a: 3 },
        { q: "Dalam kedua agama, tokoh manusia pertama yang diciptakan Tuhan adalah...", o: ["Nuh/Noah", "Adam", "Ibrahim", "Musa"], a: 1 },
        { q: "Tokoh yang terkenal dengan kebijaksanaannya dan kemampuannya berbicara dengan hewan...", o: ["Daud/David", "Sulaiman/Solomon", "Yusuf/Joseph", "Musa/Moses"], a: 1 },
        { q: "Kitab suci Zabur (Mazmur) diwahyukan kepada Nabi...", o: ["Daud/David", "Musa/Moses", "Isa/Yesus", "Ibrahim/Abraham"], a: 0 },
        { q: "Tokoh yang dibuang ke dalam sumur oleh saudara-saudaranya dan kelak menjadi petinggi di Mesir...", o: ["Yunus", "Yusuf/Joseph", "Musa", "Ismail"], a: 1 },
        { q: "Agama Islam, Kristen, dan Yahudi sering dikelompokkan dalam satu rumpun agama yaitu...", o: ["Agama Dharma", "Agama Samawi (Abrahamik)", "Agama Lokal", "Agama Timur"], a: 1 },
        { q: "Ibunda dari Nabi Isa / Yesus adalah...", o: ["Siti Hawa", "Siti Sarah", "Maryam/Maria", "Siti Hajar"], a: 2 },
        { q: "Tokoh yang diperintahkan membuat bahtera/kapal besar untuk selamat dari air bah...", o: ["Ibrahim", "Musa", "Nuh/Noah", "Luth"], a: 2 },
        { q: "Kota tempat Yesus dilahirkan (menurut tradisi Kristen) yang juga dihormati dalam Islam...", o: ["Yerusalem", "Nazaret", "Betlehem", "Mekkah"], a: 2 },
        { q: "Kitab Taurat (Torah) diturunkan kepada Nabi...", o: ["Ibrahim", "Daud", "Musa/Moses", "Isa"], a: 2 },
        { q: "Konsep percaya kepada Satu Tuhan Yang Maha Esa dalam kedua agama disebut...", o: ["Politeisme", "Monoteisme", "Panteisme", "Animisme"], a: 1 }
    ],
    logika: [
        { q: "Semua BO2 suka opor, sebagian yang suka opor memakai baju baru. Kesimpulannya...", o: ["Semua berbaju baru", "Sebagian BO2 berbaju baru", "Semua BO2 berbaju baru", "Tidak bisa ditarik kesimpulan pasti"], a: 3 },
        { q: "Deret: 2, 5, 10, 17, 26, ... Angka selanjutnya?", o: ["35", "37", "39", "41"], a: 1 },
        { q: "Ayah Budi punya 5 anak: Nana, Nene, Nini, Nono. Siapa anak kelima?", o: ["Nunu", "Budi", "Nana", "Nanya"], a: 1 },
        { q: "Berapa banyak huruf 'A' dalam kalimat: 'ALUMNI PRAKERJA BO DUA'?", o: ["3", "4", "5", "6"], a: 1 },
        { q: "Sebuah kereta listrik bergerak ke utara. Ke arah mana asapnya berhembus?", o: ["Selatan", "Utara", "Timur", "Tidak ada asap"], a: 3 },
        { q: "Bulan apa yang memiliki 28 hari?", o: ["Februari", "Semua bulan", "Januari", "Desember"], a: 1 },
        { q: "Jika 5 kucing menangkap 5 tikus dalam 5 menit, berapa kucing yang dibutuhkan untuk menangkap 100 tikus dalam 100 menit?", o: ["5", "10", "50", "100"], a: 0 },
        { q: "Kata apa yang selalu dieja salah di dalam kamus?", o: ["Kata sandang", "Kata kerja", "Salah", "Benar"], a: 2 },
        { q: "Ada 3 apel, kamu mengambil 2. Berapa apel yang kamu miliki?", o: ["1", "2", "3", "0"], a: 1 },
        { q: "Jika A = 1, B = 2, C = 3, maka C x B + A = ?", o: ["5", "6", "7", "8"], a: 2 },
        { q: "Semua unggas bertelur. Beberapa hewan air adalah unggas. Maka...", o: ["Semua hewan air bertelur", "Beberapa hewan air bertelur", "Semua unggas adalah hewan air", "Tidak ada kesimpulan"], a: 1 },
        { q: "Saya tinggi ketika muda, dan pendek ketika tua. Apakah saya?", o: ["Pohon", "Manusia", "Lilin", "Bayangan"], a: 2 },
        { q: "Jika kamu berlari menyalip orang di posisi kedua, posisi berapakah kamu sekarang?", o: ["Pertama", "Kedua", "Ketiga", "Keempat"], a: 1 },
        { q: "Angka berapa yang jika dikalikan dengan angka berapapun hasilnya akan tetap sama?", o: ["1", "10", "0", "-1"], a: 2 },
        { q: "Pintu apa yang tidak bisa didorong padahal tidak dikunci?", o: ["Pintu brankas", "Pintu Geser (Tarik)", "Pintu hatimu", "Pintu otomatis"], a: 1 }
    ],
    sastra: [
        { q: "Kutipan 'Kalau sampai waktunya, Ku mau tak seorang kan merayu...' adalah puisi karya...", o: ["W.S. Rendra", "Sapardi Djoko Damono", "Chairil Anwar", "Pramoedya A.T."], a: 2 },
        { q: "Novel 'Bumi Manusia' mengisahkan tokoh Minke ditulis oleh...", o: ["Andrea Hirata", "Pramoedya Ananta Toer", "Ahmad Fuadi", "Habiburrahman"], a: 1 },
        { q: "Majas yang melebih-lebihkan kenyataan disebut...", o: ["Personifikasi", "Metafora", "Hiperbola", "Ironi"], a: 2 },
        { q: "Cerita rakyat Malin Kundang berasal dari provinsi...", o: ["Sumatera Utara", "Sumatera Barat", "Jawa Barat", "Kalimantan Selatan"], a: 1 },
        { q: "Kumpulan surat 'Habis Gelap Terbitlah Terang' ditulis oleh...", o: ["Cut Nyak Dien", "Dewi Sartika", "R.A. Kartini", "Martha C. Tiahahu"], a: 2 },
        { q: "Buku puisi 'Hujan Bulan Juni' adalah mahakarya dari...", o: ["Chairil Anwar", "W.S. Rendra", "Sapardi Djoko Damono", "Taufiq Ismail"], a: 2 },
        { q: "Tokoh 'Si Doel Anak Sekolahan' pada awalnya merupakan karakter dari novel klasik karya...", o: ["Aman Datuk Madjoindo", "Marah Rusli", "Sutan Takdir Alisjahbana", "Armijn Pane"], a: 0 },
        { q: "Novel 'Laskar Pelangi' yang sangat fenomenal ditulis oleh...", o: ["Tere Liye", "Raditya Dika", "Andrea Hirata", "Ahmad Fuadi"], a: 2 },
        { q: "Puisi 'Karawang-Bekasi' ditulis oleh penyair berjuluk Si Binatang Jalang, yaitu...", o: ["Taufiq Ismail", "Sutardji Calzoum Bachri", "Chairil Anwar", "Goenawan Mohamad"], a: 2 },
        { q: "Majas yang membandingkan benda mati seolah-olah memiliki sifat manusia disebut...", o: ["Metafora", "Personifikasi", "Hiperbola", "Litotes"], a: 1 },
        { q: "Lakon/Drama 'Cinta itu Luka' dan novel 'Cantik Itu Luka' ditulis oleh sastrawan modern...", o: ["Eka Kurniawan", "Dee Lestari", "Ayu Utami", "Seno Gumira Ajidarma"], a: 0 },
        { q: "Cerita rakyat Sangkuriang dan Dayang Sumbi berkaitan dengan asal usul gunung...", o: ["Merapi", "Tangkuban Perahu", "Bromo", "Rinjani"], a: 1 },
        { q: "Roman legendaris 'Siti Nurbaya' (Kasih Tak Sampai) ditulis oleh...", o: ["Marah Rusli", "Hamka", "Tulis Sutan Sati", "Abdoel Moeis"], a: 0 },
        { q: "Novel 'Tenggelamnya Kapal Van der Wijck' adalah karya sastrawan ulama...", o: ["K.H. Ahmad Dahlan", "Buya Hamka", "A.A. Navis", "Kuntowijoyo"], a: 1 },
        { q: "Gaya bahasa merendahkan diri padahal kenyataannya lebih baik disebut...", o: ["Sarkasme", "Litotes", "Ironi", "Eufemisme"], a: 1 }
    ],
    ekonomi: [
        { q: "Kondisi di mana harga barang-barang secara umum mengalami kenaikan terus-menerus disebut...", o: ["Deflasi", "Devaluasi", "Inflasi", "Depresiasi"], a: 2 },
        { q: "Lembaga yang bertugas menjaga kestabilan nilai Rupiah adalah...", o: ["OJK", "Kementerian Keuangan", "Bank Indonesia (BI)", "Bursa Efek"], a: 2 },
        { q: "Harga daging naik drastis jelang Lebaran terjadi karena...", o: ["Inflasi tahunan", "Permintaan naik, Penawaran tetap", "Monopoli pasar", "Nilai Rupiah turun"], a: 1 },
        { q: "Bapak Koperasi Indonesia yang juga Wakil Presiden pertama RI adalah...", o: ["Soekarno", "Mohammad Hatta", "Sutan Sjahrir", "Adam Malik"], a: 1 },
        { q: "Tempat bertemunya penjual dan pembeli dalam ekonomi disebut...", o: ["Kantor", "Pasar", "Bank", "Bursa"], a: 1 },
        { q: "Hukum Permintaan menyatakan bahwa jika harga naik, maka jumlah barang yang diminta akan...", o: ["Tetap", "Naik", "Turun", "Berubah-ubah"], a: 2 },
        { q: "Surat berharga yang menunjukkan bukti kepemilikan bagian modal perusahaan disebut...", o: ["Obligasi", "Reksa Dana", "Saham", "Deposito"], a: 2 },
        { q: "Sistem ekonomi yang dianut oleh negara Indonesia berdasarkan UUD 1945 adalah...", o: ["Kapitalis", "Komunis", "Sistem Ekonomi Pancasila", "Liberal"], a: 2 },
        { q: "Lembaga negara yang mengawasi seluruh kegiatan di sektor jasa keuangan adalah...", o: ["BI", "OJK", "LPS", "KPK"], a: 1 },
        { q: "Nilai mata uang suatu negara yang diukur dengan mata uang negara lain disebut...", o: ["Suku Bunga", "Inflasi", "Kurs", "Devisa"], a: 2 },
        { q: "Pajak Pertambahan Nilai (PPN) di Indonesia saat ini (berdasarkan UU HPP terbaru) tarif standarnya adalah...", o: ["10%", "11%", "12%", "15%"], a: 1 },
        { q: "Tindakan mengurangi nilai mata uang negara sendiri terhadap mata uang asing oleh pemerintah disebut...", o: ["Revaluasi", "Devaluasi", "Depresiasi", "Apresiasi"], a: 1 },
        { q: "Perusahaan yang seluruh atau sebagian besar modalnya dimiliki oleh negara disebut...", o: ["PT", "CV", "BUMN", "Firma"], a: 2 },
        { q: "Kegiatan membeli barang dari luar negeri disebut...", o: ["Ekspor", "Import", "Barter", "Dumping"], a: 1 },
        { q: "Salah satu dari 15 negara pasar utama wisman ke Indonesia adalah...", o: ["Argentina", "Malaysia", "Mesir", "Brasil"], a: 1 }
    ],
    hukum: [
        { q: "Lembaga yang berwenang mengadili sengketa hasil Pemilu adalah...", o: ["Mahkamah Agung", "KPU", "Mahkamah Konstitusi", "DPR"], a: 2 },
        { q: "Hukum dasar tertulis tertinggi di Indonesia adalah...", o: ["Pancasila", "TAP MPR", "Undang-Undang", "UUD 1945"], a: 3 },
        { q: "Lembaga yang memberantas tindak pidana korupsi adalah...", o: ["Polri", "Kejaksaan Agung", "KPK", "Mahkamah Agung"], a: 2 },
        { q: "Usia minimal mendapatkan Kartu Tanda Penduduk (KTP) adalah...", o: ["15 Tahun", "17 Tahun", "18 Tahun", "21 Tahun"], a: 1 },
        { q: "Hak Cipta sebuah lagu masuk ke ranah hukum...", o: ["Hukum Pidana", "Hukum Tata Negara", "Hukum Kekayaan Intelektual", "Hukum Internasional"], a: 2 },
        { q: "Asas hukum: seseorang dianggap tidak bersalah sampai dibuktikan sebaliknya di pengadilan adalah...", o: ["Asas Legalitas", "Presumption of Innocence", "Asas Praduga Bersalah", "Asas Lex Specialis"], a: 1 },
        { q: "Rancangan Undang-Undang (RUU) dibahas dan disetujui bersama oleh Presiden dan...", o: ["MPR", "DPD", "DPR", "Mahkamah Agung"], a: 2 },
        { q: "Lembaga yang bertugas menjaga kehormatan martabat hakim adalah...", o: ["Mahkamah Konstitusi", "Komisi Yudisial", "DPR", "Komnas HAM"], a: 1 },
        { q: "Pembunuhan berencana dalam KUHP Indonesia biasanya diancam dengan pasal...", o: ["338", "340", "362", "378"], a: 1 },
        { q: "Mencuri barang milik orang lain diatur dalam Hukum...", o: ["Hukum Perdata", "Hukum Tata Usaha Negara", "Hukum Pidana", "Hukum Adat"], a: 2 },
        { q: "Surat Izin Mengemudi (SIM) C di Indonesia diperuntukkan bagi pengemudi...", o: ["Mobil Penumpang", "Truk Besar", "Sepeda Motor", "Kendaraan Umum"], a: 2 },
        { q: "Badan yang berwenang memeriksa pengelolaan tanggung jawab keuangan negara adalah...", o: ["KPK", "BPK", "Kementerian Keuangan", "DPR"], a: 1 },
        { q: "Orang yang memberikan jasa hukum, baik di dalam maupun luar pengadilan disebut...", o: ["Jaksa", "Hakim", "Polisi", "Advokat / Pengacara"], a: 3 },
        { q: "Undang-Undang ITE sering digunakan untuk menjerat kasus tindak pidana di dunia...", o: ["Lalu Lintas", "Perbankan", "Siber / Internet", "Lingkungan Hidup"], a: 2 },
        { q: "Perjanjian sewa-menyewa rumah termasuk ke dalam ranah hukum...", o: ["Hukum Perdata", "Hukum Pidana", "Hukum Internasional", "Hukum Konstitusi"], a: 0 }
    ]
};
